---

- name: General Config
  hosts: iosxe
  gather_facts: no
  

  tasks:

  - name: Add banner

    ios_banner:
      banner: login
      text: HLAB router login
      state: present
  
  - name: change hostname and add NTP server
    ios_config:
      lines:
        - hostname hlab-8000v
        - ntp server 192.168.1.102

  - name: change description
    ios_config:
      lines:
        - description - Config by ansible
      parents: Interface GigabitEthernet1




